version: 2
jobs:
  test-server:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - run:
          name: Set up python tools for backend
          command: |
            sudo apt update -y
            make install-smartcard
            make build-dev
      - run:
          name: Run Python Tests and Coverage
          command: |
            make coverage
      - run:
          name: Run Mypy Type Checking
          command: |
            make typecheck

workflows:
  version: 2
  test-server:
    jobs:
      - test-server
